# Railway Configuration for Eternalgy EMS Backend

[build]
builder = "NIXPACKS"
nixpacksConfigPath = "backend/nixpacks.toml"
watchPaths = ["backend/**"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
