# Railway Configuration for Eternalgy EMS
# This file is for the root service - Railway will auto-detect backend and frontend as separate services

[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
