[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build",
  "node scripts/sync-frontend.js"
]

[start]
cmd = "cd backend && npm start"
