[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18"]

# Install both backend and frontend dependencies.
# Use conditional paths so this works whether Railway builds from repo root or from the backend service path.
[phases.install]
cmds = [
  "if [ -d backend ]; then npm --prefix backend ci; else npm ci; fi",
  "if [ -d frontend ]; then npm --prefix frontend ci --include=dev; else npm --prefix ../frontend ci --include=dev; fi"
]

# Build the frontend and sync the dist into backend/public before starting the server.
[phases.build]
cmds = [
  "if [ -d frontend ]; then npm --prefix frontend run build; else npm --prefix ../frontend run build; fi",
  "if [ -f scripts/sync-frontend.js ]; then node scripts/sync-frontend.js; else node ../scripts/sync-frontend.js; fi"
]

[start]
cmd = "if [ -d backend ]; then cd backend && npm start; else npm start; fi"
